version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_PUBLIC_URL=${DATABASE_PUBLIC_URL}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data: 